# -*- coding: utf-8 -*-
"""AI-Robotics Midterm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWy0XV_G0ZZbpbE1y2BOLi4L8_TAtFvh

# Temporal Cycle-Consistency Learning
## Self-supervised video representations with TCN $\rightarrow$ TCC using `aegean-ai/tcc`

This notebook is designed to read like a **tutorial** and a **course assignment** at the same time.

It focuses on one question:

> Can a self-supervised video representation learn the **latent phase** of a task purely from temporal structure, without robot control, action labels, or transcription?

The answer developed across the two Google Research papers is:

1. **TCN** learns by enforcing *time-based contrastive alignment* under strong synchronization assumptions.
2. **TCC** generalizes this idea by enforcing *temporal cycle-consistency*, which is more robust to variations in execution speed and alignment.

In this notebook you will:

- study the conceptual evolution from **TCN** to **TCC**
- train the **PyTorch rewrite** in `aegean-ai/tcc`
- extract frame embeddings
- visualize trajectories with **PCA**, **t-SNE**, and **UMAP**
- segment action sequences using representation geometry

## Papers

- Sermanet et al., **Time-Contrastive Networks**, 2018  
  https://arxiv.org/abs/1704.06888

- Dwibedi et al., **Temporal Cycle-Consistency Learning**, 2019  
  https://arxiv.org/abs/1904.07846

## Repository used in this notebook

- `https://github.com/aegean-ai/tcc`  
  This notebook assumes the **`main` branch** and the current PyTorch package layout under `src/tcc/`.

## What you should learn

By the end, you should be able to explain why TCN and TCC are related but not identical:

- TCN: **metric alignment with synchronized positives**
- TCC: **structural temporal alignment via cycles**

A useful mental model is:

- TCN says: *"frames at the same time index should be close."*
- TCC says: *"if I map from one sequence to another and back, I should return to the same temporal phase."*

## 1. Theory recap: from TCN to TCC

### 1.1 TCN: contrastive temporal alignment

TCN learns an embedding
$$
z_t = f_\theta(I_t)
$$
so that synchronized frames from different views become neighbors in feature space.

A canonical triplet-style loss is:
$$
\mathcal{L}_{\mathrm{TCN}}
=
\max\left(
0,\;
\|f(I_t^a)-f(I_t^b)\|_2^2
-
\|f(I_t^a)-f(I_{t'}^b)\|_2^2
+
\alpha
\right).
$$

Interpretation:

- **anchor:** frame $I_t^a$
- **positive:** synchronized frame $I_t^b$
- **negative:** mismatched-time frame $I_{t'}^b$

This already encodes an important idea: **time is supervision**.

But TCN assumes that corresponding frames are available at matching time indices, which is a strong assumption.

### 1.2 Why TCN is not enough

Suppose two people perform the same pouring task:

- one moves slowly
- one moves quickly
- one pauses before tilting
- one starts tilting earlier

Then the frame with semantic phase "tilt begins" is **not** guaranteed to occur at the same time index in both videos.

So absolute time matching becomes fragile.

### 1.3 TCC: align temporal structure, not raw clock time

TCC keeps the idea that embeddings should reflect task progression, but replaces hard synchronized matching with **cycle consistency**.

**Conceptual intuition.** Given frame $i$ in sequence $A$, map it to the most corresponding frame in sequence $B$:
$$
j = \arg\min_k \|f(I_i^A)-f(I_k^B)\|.
$$

Then map back from sequence $B$ to sequence $A$:
$$
i' = \arg\min_l \|f(I_j^B)-f(I_l^A)\|.
$$

TCC encourages $i' \approx i$.

**Differentiable training loss.** The hard `argmin` above is not differentiable, so the actual TCC loss replaces it with a **soft nearest-neighbor** formulation. For frame $i$ in sequence $A$, define a soft correspondence distribution over frames in sequence $B$:

$$
\beta_k^{(i)} = \frac{\exp(-\|f(I_i^A) - f(I_k^B)\|^2 / \tau)}{\sum_{k'} \exp(-\|f(I_i^A) - f(I_{k'}^B)\|^2 / \tau)}
$$

where $\tau$ is a temperature parameter. The cycle-back distribution is computed analogously, and the loss is the cross-entropy between the back-mapped distribution and a target concentrated at the original index $i$. This makes the entire cycle differentiable and trainable with standard gradient descent.

Conceptually:

- TCN aligns **absolute timestamps**
- TCC aligns **latent phase structure**

This is why TCC is more appropriate when demonstrations are semantically similar but **temporally warped**.

### 1.4 What the embedding should look like on pouring

If TCC works, then the learned trajectory in embedding space should behave like a latent phase variable:

- early reach frames cluster near other early reach frames
- grasp transitions appear near one another
- tilt and pour form coherent regions
- embeddings from different videos should trace similar temporal paths

That is the premise you will test below.

## 2. How this notebook and the `aegean-ai/tcc` repo work together

This notebook is **not** a standalone script. It is a guided analysis layer that drives the `aegean-ai/tcc` PyTorch package. The repo provides the training loop, model definitions, dataset utilities, and evaluation code. The notebook provides the experimental protocol: configuring runs, extracting embeddings, and visualizing results.

### Two supported environments

| | **Dev container (recommended)** | **Google Colab** |
|---|---|---|
| **GPU** | Local NVIDIA GPU via Docker | Colab T4/A100 runtime |
| **Package manager** | `uv` (pre-installed in container) | `pip` (Colab default) |
| **Setup effort** | `make start` — one command | Clone + pip install in notebook cells |
| **Persistence** | Full local disk | Session-scoped (data lost on disconnect) |
| **Best for** | Full sweep, large runs | Quick experiments, no local GPU |

Choose **one** environment and follow the corresponding setup path in Section 3.

### Workflow overview

```
┌──────────────────────────────────────────────────────────────────┐
│  This notebook (analysis layer)                                  │
│                                                                  │
│  1. Set up environment (dev container OR Colab)                  │
│  2. Prepare the pouring dataset                                  │
│  3. Configure training via tcc.config.get_default_config()       │
│  4. Launch training via tcc.train.train(cfg)                     │
│  5. Load checkpoints via tcc.train.load_checkpoint()             │
│  6. Extract embeddings via tcc.evaluate.get_embeddings_dataset() │
│  7. Visualize and segment (PCA, UMAP, KMeans — notebook code)   │
└──────────────────────────────────────────────────────────────────┘
         │                        ▲
         │  function calls        │  returns tensors,
         ▼                        │  checkpoints, configs
┌──────────────────────────────────────────────────────────────────┐
│  aegean-ai/tcc  (installed as editable package)                  │
│                                                                  │
│  src/tcc/                                                        │
│  ├── config.py          TCCConfig dataclass + get_default_config │
│  ├── train.py           Training loop, checkpoint save/load      │
│  ├── evaluate.py        Embedding extraction, eval metrics       │
│  ├── datasets.py        DataConfig, create_dataset()             │
│  ├── models.py          ResNet backbone + embedding head         │
│  ├── alignment.py       TCC alignment algorithm                  │
│  ├── losses.py          Cycle-consistency loss                   │
│  └── algos/             Algorithm registry (tcc, tcn, sal, …)    │
│                                                                  │
│  configs/                                                        │
│  └── default.yaml       Default hyperparameters                  │
│                                                                  │
│  scripts/                                                        │
│  └── download_pouring_data.sh                                    │
│                                                                  │
│  src/tcc/dataset_preparation/                                    │
│  ├── videos_to_dataset.py    Raw videos → image folders          │
│  ├── images_to_dataset.py    Images → dataset structure          │
│  └── visualize_dataset.py    Inspect prepared data               │
└──────────────────────────────────────────────────────────────────┘
```

### What you modify vs. what you use as-is

| Layer | You modify | You use as-is |
|-------|-----------|---------------|
| **Notebook** | Embedding dimension, iteration count, analysis parameters ($k$, projection method) | Visualization and segmentation code |
| **Repo config** | `model.conv_embedder.embedding_size`, `train.max_iters`, `logdir` | Everything else in `configs/default.yaml` |
| **Repo code** | Nothing — treat as a library | `train.py`, `evaluate.py`, `datasets.py`, `models.py` |

## 3. Environment setup

Choose **one** of the two paths below. Both result in a working `import tcc` with GPU access.

---

### Path A: Dev container (recommended for full assignment)

The repo ships a complete Docker-based development environment with GPU support, `uv`, and VS Code integration.

**Prerequisites:** Docker with NVIDIA Container Toolkit, VS Code with Dev Containers extension.

**Steps:**

1. Clone the repo locally:
   ```bash
   git clone https://github.com/aegean-ai/tcc && cd tcc
   ```
2. Copy the environment file:
   ```bash
   cp .env.example .env
   # Edit .env to add WANDB_API_KEY and/or HF_TOKEN if needed
   ```
3. Open in VS Code → "Reopen in Container" (or run `docker compose up -d` manually).
4. Inside the container, run:
   ```bash
   make start
   ```
   This creates a `.venv` with `uv`, installs the package in editable mode, and registers a Jupyter kernel.
5. Open this notebook in VS Code or JupyterLab (port 8888) and select the **"Python 3 (tcc)"** kernel.

**Key details:**
- Base image: `pytorch/pytorch:2.7.1-cuda12.8-cudnn9-runtime`
- Package manager: `uv` (not pip) — the Makefile handles all `uv` calls
- Python: whatever 3.11+ is in the container (typically from conda)
- Workspace: `/workspaces/tcc`
- TensorBoard: port 6006

**Installing extra notebook dependencies** (matplotlib, umap-learn, etc.):
```bash
make install-notebooks
```

---

### Path B: Google Colab (quick start, no local GPU needed)

Use this path if you do not have a local GPU or want a fast start. Colab sessions are ephemeral — save checkpoints to Google Drive to avoid losing training results.

**Steps:**

1. In a Colab notebook, enable GPU: **Runtime → Change runtime type → T4 GPU**.
2. Run the clone and install cells below (Section 3.1–3.2).
3. Colab uses `pip` — the `%pip install` commands handle everything.

**Limitations:**
- Session timeout erases all local files. Mount Google Drive for persistence:
  ```python
  from google.colab import drive
  drive.mount('/content/drive')
  # Point EXPERIMENT_ROOT and DATA_ROOT to /content/drive/MyDrive/tcc/
  ```
- Colab's default Python may differ from 3.11 — the package should still install but is only tested on 3.11–3.12.

---

### Python version requirement

The repo requires **Python ≥3.11, <3.13** (`pyproject.toml`). The dev container satisfies this automatically. On Colab, check with `!python --version`.
"""

from google.colab import drive
drive.mount('/content/drive')

import sys, platform, os, pathlib

print("Python:", sys.version)
print("Platform:", platform.platform())
print("Working directory:", os.getcwd())

"""### 3.1 Clone the repository (Colab / Path B only)

If you are using the **dev container** (Path A), skip this — the repo is already your workspace at `/workspaces/tcc`.
"""

import subprocess, pathlib

REPO_URL = "https://github.com/aegean-ai/tcc"
REPO_DIR = pathlib.Path("tcc")

if not REPO_DIR.exists():
    subprocess.run(["git", "clone", REPO_URL, str(REPO_DIR)], check=False)
else:
    print("Repository already exists:", REPO_DIR)

print("Repo dir exists:", REPO_DIR.exists())

"""### 3.2 Install the package (Colab / Path B only)

If you are using the **dev container** (Path A), skip this — `make start` already installed the package. Run `make install-notebooks` if you need matplotlib/umap-learn.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -e ./tcc
# %pip install matplotlib scikit-learn umap-learn tqdm pyyaml

import tcc
print("tcc installed successfully")

import importlib
try:
    importlib.import_module("tcc")
    print("tcc package is available.")
except ModuleNotFoundError:
    print("tcc not found. Follow the install instructions for your environment (Path A or B).")

"""### 3.3 Quick repository inspection

Verify the repo structure. In the dev container the repo root is `/workspaces/tcc`; on Colab it is the cloned `tcc/` directory.
"""

import os

# Detect environment: dev container vs Colab
REPO_ROOT = pathlib.Path("/workspaces/tcc") if pathlib.Path("/workspaces/tcc/src/tcc").exists() else REPO_DIR

def walk_top(path, max_depth=2):
    base = os.path.abspath(path)
    label = os.path.basename(base)
    for root, dirs, files in os.walk(base):
        depth = root[len(base):].count(os.sep)
        if depth <= max_depth:
            print(root.replace(base, label))
            for f in files[:10]:
                print("   ", f)

walk_top(str(REPO_ROOT), max_depth=2)

"""## 4. Data: the pouring dataset

The multiview pouring dataset is hosted on HuggingFace at [`sermanet/multiview-pouring`](https://huggingface.co/datasets/sermanet/multiview-pouring). It contains TFRecord files with multi-view video sequences of pouring tasks.

### Download from HuggingFace

Use `huggingface_hub` to download the dataset files. The code cell below clones the dataset repository into `data/pouring/`. This is the recommended approach — it downloads all TFRecord files and the recombination script needed for one split file.

### Expected directory layout

After download and conversion, the dataset root must have this structure:

```
data/pouring_processed/pouring/
├── train/
│   ├── video_001/
│   │   ├── frame_0000.png
│   │   ├── frame_0001.png
│   │   └── ...
│   ├── video_002/
│   │   └── ...
│   └── ...
└── val/
    ├── video_050/
    │   └── ...
    └── ...
```

Each video is a directory of sequentially numbered frames. The PyTorch `create_dataset` function expects this layout — it discovers videos by listing subdirectories under `train/` or `val/`, then loads frames in filename-sorted order.
"""

DATA_ROOT = pathlib.Path("data")
RAW_POURING_ROOT = DATA_ROOT / "pouring"
PROCESSED_POURING_ROOT = DATA_ROOT / "pouring_processed"

RAW_POURING_ROOT.mkdir(parents=True, exist_ok=True)
PROCESSED_POURING_ROOT.mkdir(parents=True, exist_ok=True)

print("Raw data dir:", RAW_POURING_ROOT.resolve())
print("Processed data dir:", PROCESSED_POURING_ROOT.resolve())

"""### 4.1 Download from HuggingFace

The dataset is hosted at [`sermanet/multiview-pouring`](https://huggingface.co/datasets/sermanet/multiview-pouring) and contains TFRecord files organized into `train/`, `val/`, and `test/` splits.

Use `huggingface_hub.snapshot_download` to download the full dataset. This downloads all files (TFRecords, recombination scripts, README) into a local cache and returns the path. We then symlink or copy into our expected `data/pouring/` directory.

> **Note:** One test file (`whiteorange_to_clear1_real`) was split into two parts due to upload size limits. After downloading, run the provided shell script to recombine it. This only affects the test split — training and validation are ready to use immediately.
"""

from huggingface_hub import snapshot_download

# Download the full dataset from HuggingFace (progress bars suppressed for clean output)
hf_cache_path = snapshot_download(
    repo_id="sermanet/multiview-pouring",
    repo_type="dataset",
    local_dir=str(RAW_POURING_ROOT),
)

print("Dataset downloaded to:", hf_cache_path)

# List what was downloaded
for split_dir in sorted(RAW_POURING_ROOT.iterdir()):
    if split_dir.is_dir() and not split_dir.name.startswith("."):
        tfrecords = list(split_dir.glob("*.tfrecord*"))
        print(f"  {split_dir.name}/: {len(tfrecords)} TFRecord file(s)")

!ls tcc/src/tcc/dataset_preparation

!ls data/pouring

!ls data/pouring/videos | head

!ls data/pouring/tfrecords | head

!ls data/pouring/tfrecords/train | head

!ls data/pouring/videos/train | head

!python tcc/src/tcc/dataset_preparation/videos_to_dataset.py \
  --input-dir data/pouring/videos/train \
  --output-dir data/pouring_processed \
  --name pouring \
  --file-pattern "*.mov" \
  --width 224 \
  --height 224

!ls data/pouring_processed/pouring

!ls data/pouring_processed/pouring | head

!ls data/pouring_processed/pouring/clearodwalla_to_clear1_real_view0 | head

import sys
sys.path.append("tcc/src")

from tcc.config import get_default_config
from tcc.train import train

cfg = get_default_config()
print(cfg)

cfg = get_default_config()

cfg.datasets = ['pouring']
cfg.path_to_tfrecords = "data/%s/tfrecords"

cfg.train.max_iters = 100
cfg.model.conv_embedder.embedding_size = 32

# Step 1: Download is handled above via huggingface_hub (cell 4.1)

# Step 2 (optional): Recombine the split test file
# Only needed if you plan to use the test split
# !bash {RAW_POURING_ROOT}/tfrecords/test/whiteorange_to_clear1_real_combining.sh


#!python -m tcc.dataset_preparation.videos_to_dataset ...

#print("After downloading from HuggingFace, convert the TFRecords to image folders.")

"""### 4.2 Expected semantic phases

We will reason about pouring in terms of latent phases such as:

1. reach
2. grasp
3. lift / position
4. tilt
5. pour
6. retract / return

You do **not** need action labels for TCC training.  
These phase names are used only for qualitative interpretation of the learned representation.

## 5. Configuration and training

The current `aegean-ai/tcc` package provides:

- a typed configuration object
- an `alignment` algorithm corresponding to TCC
- a PyTorch training loop

The default configuration is useful to inspect first, because it tells us:

- training algorithm
- dataset name
- image size
- batch size
- embedding size
- checkpoint/logging schedule
"""

from pprint import pprint

try:
    from tcc.config import get_default_config
    cfg = get_default_config()
    print(cfg)
except Exception as e:
    print("Could not import tcc yet:", repr(e))
    cfg = None

"""### 5.1 Utility: robust config editing

Research repositories evolve. Rather than assuming one exact config layout, we use helper functions that can set values safely if the corresponding fields exist.

This makes the notebook more resilient to small refactors of the dataclass hierarchy.
"""

def set_if_exists(obj, path, value):
    parts = path.split(".")
    cur = obj
    for p in parts[:-1]:
        if not hasattr(cur, p):
            return False
        cur = getattr(cur, p)
    if hasattr(cur, parts[-1]):
        setattr(cur, parts[-1], value)
        return True
    return False

def get_if_exists(obj, path, default=None):
    parts = path.split(".")
    cur = obj
    for p in parts:
        if not hasattr(cur, p):
            return default
        cur = getattr(cur, p)
    return cur

def summarize_config(cfg):
    keys = [
        "training_algo",
        "datasets",
        "path_to_tfrecords",
        "logdir",
        "train.batch_size",
        "train.max_iters",
        "train.num_frames",
        "eval.batch_size",
        "model.embedder_type",
        "model.conv_embedder.embedding_size",
        "model.base_model.train_base",
        "optimizer.type",
        "optimizer.lr.initial_lr",
        "data.image_size",
        "data.frame_stride",
        "data.num_steps",
    ]
    rows = []
    for k in keys:
        rows.append((k, get_if_exists(cfg, k)))
    return rows

if cfg is not None:
    for k, v in summarize_config(cfg):
        print(f"{k:40s} {v}")

"""### 5.2 Choose experiment settings

The assignment requires an embedding-dimension sweep:

- 32
- 64
- 128

We keep everything else as close as possible to the repo defaults so that the experiment isolates the representation bottleneck dimension.
"""

EMBED_DIMS = [32, 64, 128]
EXPERIMENT_ROOT = pathlib.Path("runs_tutorial")
EXPERIMENT_ROOT.mkdir(exist_ok=True)

print("Experiments will be stored in:", EXPERIMENT_ROOT.resolve())
print("Embedding dims:", EMBED_DIMS)

!ls

"""### 5.3 Build a training config for one run

The training code in `src/tcc/train.py` expects a `TCCConfig`, and the default config already uses:

- `datasets: [pouring]`
- `training_algo: alignment`

We modify:

- embedding size
- log directory
- dataset root
- optionally `train.max_iters` for a shorter tutorial run
"""

def make_run_config(embed_dim=128, max_iters=2000, logdir=None):
    from tcc.config import get_default_config

    cfg = get_default_config()

    set_if_exists(cfg, "training_algo", "alignment")
    set_if_exists(cfg, "datasets", ["pouring"])
    set_if_exists(cfg, "train.max_iters", max_iters)
    set_if_exists(cfg, "model.conv_embedder.embedding_size", embed_dim)

    # notebook's dataset root override
    ds_fmt = str((PROCESSED_POURING_ROOT / "%s").resolve())
    set_if_exists(cfg, "path_to_tfrecords", ds_fmt)

    # fix for short videos
    set_if_exists(cfg, "data.frame_stride", 5)
    set_if_exists(cfg, "train.num_frames", 10)

    # notebook's experiment logdir override
    if logdir is None:
        logdir = str((EXPERIMENT_ROOT / f"pouring_tcc_d{embed_dim}").resolve())
    set_if_exists(cfg, "logdir", logdir)

    return cfg

try:
    demo_cfg = make_run_config(embed_dim=64, max_iters=500)
    for k, v in summarize_config(demo_cfg):
        print(f"{k:40s} {v}")
except Exception as e:
    print("Config construction failed:", repr(e))

cfg_test = make_run_config(embed_dim=64, max_iters=50)
print("LOGDIR:", cfg_test.logdir)
print("DATA:", cfg_test.path_to_tfrecords)

"""## 6. Training

The training loop in the repo is exposed through `tcc.train.train(cfg)`.

The logic is:

1. instantiate the algorithm corresponding to `cfg.training_algo`
2. build the dataset loader
3. optimize the alignment loss
4. save checkpoints in `cfg.logdir`
"""

import os, shutil, pathlib

src = pathlib.Path("/content/data/pouring_processed/pouring")
dst = pathlib.Path("/tmp/pouring_tfrecords")

print("SRC exists:", src.exists(), src)
print("DST exists before:", dst.exists(), dst)

if not src.exists():
    raise FileNotFoundError(f"Source dataset not found: {src}")

if dst.exists() or dst.is_symlink():
    try:
        if dst.is_symlink() or dst.is_file():
            dst.unlink()
        else:
            shutil.rmtree(dst)
    except Exception as e:
        print("Could not clear old dst:", e)

os.symlink(src, dst)

print("DST exists after:", dst.exists())
print("Symlink target:", os.readlink(dst))
print("Example entries:", os.listdir(dst)[:10])

!ls /tmp/pouring_tfrecords | head

from tcc.config import get_default_config
from tcc.train import train
import os

cfg32 = get_default_config()
cfg32.training_algo = "alignment"
cfg32.datasets = ["pouring"]
cfg32.path_to_tfrecords = "/tmp/%s_tfrecords/"
cfg32.train.max_iters = 300
cfg32.train.num_frames = 10
cfg32.data.frame_stride = 5
cfg32.model.conv_embedder.embedding_size = 32
cfg32.logdir = "/content/runs_tutorial/pouring_tcc_d32"

cfg32.logging.report_interval = 10
cfg32.checkpoint.save_interval = 100

os.makedirs(cfg32.logdir, exist_ok=True)

print("TRAIN32 logdir:", cfg32.logdir)
print("TRAIN32 data:", cfg32.path_to_tfrecords % "pouring")
print("REPORT EVERY:", cfg32.logging.report_interval)
print("SAVE EVERY:", cfg32.checkpoint.save_interval)

train(cfg32)

!ls /content/runs_tutorial/pouring_tcc_d32

!find /content/runs_tutorial -maxdepth 2 -name "checkpoint_*.pt"

cfg32 = make_run_config(embed_dim=32, max_iters=1000)
print("cfg32.logdir =", cfg32.logdir)

from pathlib import Path

cfg32 = make_run_config(embed_dim=32, max_iters=1000)
cfg32.logdir = "/content/runs_tutorial/pouring_tcc_d32"
cfg32.path_to_tfrecords = "/tmp/%s_tfrecords/"

print("cfg32.logdir =", cfg32.logdir)
print("cfg32.path_to_tfrecords =", cfg32.path_to_tfrecords)
print("checkpoint_50 exists:", Path("/content/runs_tutorial/pouring_tcc_d32/checkpoint_50.pt").exists())
print("checkpoint_1000 exists:", Path("/content/runs_tutorial/pouring_tcc_d32/checkpoint_1000.pt").exists())

from pathlib import Path

def latest_checkpoint(logdir):
    candidates = sorted(Path(logdir).glob("checkpoint_*.pt"))
    if not candidates:
        return None
    return str(candidates[-1])

def run_training(cfg):
    from tcc.train import train
    print("Starting training with logdir:", cfg.logdir)
    train(cfg)

# Example debug run:
cfg_debug = make_run_config(embed_dim=32, max_iters=50)
run_training(cfg_debug)

#print("Uncomment the debug run once the dataset path is ready.")

"""### 6.1 Full assignment runs

Run three experiments:

- $D=32$
- $D=64$
- $D=128$
"""

max_iters = 2000
def make_run_config(embed_dim, max_iters):
    cfg = get_default_config()

    cfg.model.conv_embedder.embedding_size = embed_dim
    cfg.train.max_iters = max_iters

    # FIX for short videos
    cfg.data.frame_stride = 5
    cfg.train.num_frames = 10

    return cfg

!ls runs_tutorial

"""## 7. Loading checkpoints and extracting embeddings

The repo provides the pieces we need:

- `get_algo(...)` to instantiate the TCC algorithm
- checkpoint loading utilities from `tcc.train`
- embedding extraction utilities from `tcc.evaluate`
"""

def latest_checkpoint(logdir):
    candidates = sorted(Path(logdir).glob("checkpoint_*.pt"))
    return str(candidates[-1])

import torch
from pathlib import Path

def latest_checkpoint(logdir):
    candidates = sorted(Path(logdir).glob("checkpoint_*.pt"))
    if not candidates:
        return None
    return str(candidates[-1])

def load_trained_algo(cfg, checkpoint_path=None):
    from tcc.algos.registry import get_algo
    from tcc.train import load_checkpoint

    algo = get_algo(cfg.training_algo, cfg=cfg)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    algo = algo.to(device)

    if checkpoint_path is None:
        checkpoint_path = latest_checkpoint(cfg.logdir)

    if checkpoint_path is None:
        raise FileNotFoundError(f"No checkpoint found in {cfg.logdir}")

    _ = load_checkpoint(checkpoint_path, algo, optimizer=None)
    algo.eval()
    return algo, device, checkpoint_path

cfg32 = make_run_config(embed_dim=32, max_iters=1000)
cfg32.logdir = "/content/runs_tutorial/pouring_tcc_d32"
cfg32.path_to_tfrecords = "/tmp/%s_tfrecords/"
cfg32.train.num_frames = 10
cfg32.eval.num_frames = 10
cfg32.data.frame_stride = 5

ckpt32 = "/content/runs_tutorial/pouring_tcc_d32/checkpoint_1000.pt"

algo, device, checkpoint_path = load_trained_algo(cfg32, checkpoint_path=ckpt32)
print("Loaded checkpoint:", checkpoint_path)

loader = make_eval_dataloader(cfg32, split="val", mode="eval")

from tcc.evaluate import get_embeddings_dataset
emb_bundle32 = get_embeddings_dataset(algo, loader, device=device, max_embs=0)

print("Videos:", len(emb_bundle32["embeddings_list"]))
print("Flat embedding shape:", emb_bundle32["embeddings"].shape)

#PCA trajectory
Z32 = emb_bundle32["embeddings_list"][0]
plot_single_trajectory(Z32, method="pca", title="PCA trajectory (D=32)")

#UMAP Trajectory
if HAS_UMAP:
    plot_single_trajectory(Z32, method="umap", title="UMAP trajectory (D=32)")

#Cross Video Overlay
plot_multiple_trajectories(
    emb_bundle32["embeddings_list"],
    emb_bundle32.get("names", None),
    method="umap" if HAS_UMAP else "pca"
)

#Change Point + KMeans Segmentation
d32 = change_point_scores(Z32)
boundaries32, thr32 = detect_boundaries(d32, threshold_quantile=0.98, min_gap=8)
labels_km32 = cluster_kmeans(Z32, k=6)

plot_segmentation(
    Z32,
    labels=labels_km32,
    boundaries=boundaries32,
    title="KMeans k=6 (D=32)"
)

!ls /content/runs_tutorial
!ls /content/runs_tutorial/pouring_tcc_d64

from tcc.config import get_default_config
from tcc.train import train
import os

cfg64 = get_default_config()
cfg64.training_algo = "alignment"
cfg64.datasets = ["pouring"]
cfg64.path_to_tfrecords = "/tmp/%s_tfrecords/"
cfg64.train.max_iters = 1000
cfg64.train.num_frames = 10
cfg64.data.frame_stride = 5
cfg64.model.conv_embedder.embedding_size = 64
cfg64.logdir = "/content/runs_tutorial/pouring_tcc_d64"

cfg64.logging.report_interval = 10
cfg64.checkpoint.save_interval = 100

os.makedirs(cfg64.logdir, exist_ok=True)

print("TRAIN64 logdir:", cfg64.logdir)
print("TRAIN64 data:", cfg64.path_to_tfrecords % "pouring")

train(cfg64)

!ls /content/runs_tutorial/pouring_tcc_d64

# D=64 Extraction
cfg64 = make_run_config(embed_dim=64, max_iters=1000)
cfg64.logdir = "/content/runs_tutorial/pouring_tcc_d64"
cfg64.path_to_tfrecords = "/tmp/%s_tfrecords/"
cfg64.train.num_frames = 10
cfg64.eval.num_frames = 10
cfg64.data.frame_stride = 5

ckpt64 = "/content/runs_tutorial/pouring_tcc_d64/checkpoint_1000.pt"

algo, device, checkpoint_path = load_trained_algo(cfg64, checkpoint_path=ckpt64)
loader = make_eval_dataloader(cfg64, split="val", mode="eval")
emb_bundle64 = get_embeddings_dataset(algo, loader, device=device, max_embs=0)
print("Loaded:", checkpoint_path)
print("Shape:", emb_bundle64["embeddings"].shape)

from pathlib import Path
import numpy as np
from tcc.evaluate import get_embeddings_dataset

def test_checkpoint_for_valid_embeddings(cfg, ckpt_path, split="val", max_embs=0):
    algo, device, checkpoint_path = load_trained_algo(cfg, checkpoint_path=str(ckpt_path))
    loader = make_eval_dataloader(cfg, split=split, mode="eval")
    bundle = get_embeddings_dataset(algo, loader, device=device, max_embs=max_embs)

    valid_videos = 0
    for Z in bundle["embeddings_list"]:
        Z = np.asarray(Z)
        if Z.ndim == 2 and len(Z) >= 2 and np.isfinite(Z).all():
            valid_videos += 1

    return bundle, valid_videos

cfg64 = make_run_config(embed_dim=64, max_iters=1000)
cfg64.logdir = "/content/runs_tutorial/pouring_tcc_d64"
cfg64.path_to_tfrecords = "/tmp/%s_tfrecords/"
cfg64.train.num_frames = 10
cfg64.eval.num_frames = 10
cfg64.data.frame_stride = 5

ckpts64 = sorted(Path(cfg64.logdir).glob("checkpoint_*.pt"))
print("D64 checkpoints:", [p.name for p in ckpts64])

good_bundle64 = None
good_ckpt64 = None

for ckpt in ckpts64:
    try:
        bundle, valid_videos = test_checkpoint_for_valid_embeddings(cfg64, ckpt, split="val", max_embs=0)
        print(ckpt.name, "valid_videos =", valid_videos)
        if valid_videos > 0:
            good_bundle64 = bundle
            good_ckpt64 = str(ckpt)
            break
    except Exception as e:
        print(ckpt.name, "failed with:", repr(e))

print("Chosen checkpoint:", good_ckpt64)

emb_bundle64 = good_bundle64

# choose first fully finite video
import numpy as np
idx64 = None
for i, Z in enumerate(emb_bundle64["embeddings_list"]):
    Z = np.asarray(Z)
    if Z.ndim == 2 and len(Z) >= 2 and np.isfinite(Z).all():
        idx64 = i
        break

print("Using video index:", idx64)

Z64 = np.asarray(emb_bundle64["embeddings_list"][idx64])

plot_single_trajectory(Z64, method="pca", title="PCA trajectory (D=64)")
if HAS_UMAP:
    plot_single_trajectory(Z64, method="umap", title="UMAP trajectory (D=64)")

plot_multiple_trajectories(
    [np.asarray(Z) for Z in emb_bundle64["embeddings_list"] if np.asarray(Z).ndim == 2 and len(np.asarray(Z)) >= 2 and np.isfinite(np.asarray(Z)).all()],
    emb_bundle64.get("names", None),
    method="umap" if HAS_UMAP else "pca"
)

d64 = change_point_scores(Z64)
boundaries64, thr64 = detect_boundaries(d64, threshold_quantile=0.98, min_gap=8)
labels_km64 = cluster_kmeans(Z64, k=6)

plot_segmentation(Z64, labels=labels_km64, boundaries=boundaries64, title="KMeans k=6 (D=64)")

"""The D=64 run showed instability at later checkpoints, producing NaN embeddings for some videos. I used the earliest stable checkpoint for visualization and segmentation. This behavior is itself a useful failure mode indicating optimization instability."""

from pathlib import Path
import numpy as np
from tcc.evaluate import get_embeddings_dataset

def find_valid_checkpoint(cfg):
    ckpts = sorted(Path(cfg.logdir).glob("checkpoint_*.pt"))
    print("Found checkpoints:", [c.name for c in ckpts])

    for ckpt in ckpts:
        try:
            print("Testing:", ckpt.name)

            algo, device, _ = load_trained_algo(cfg, checkpoint_path=str(ckpt))
            loader = make_eval_dataloader(cfg, split="val", mode="eval")
            bundle = get_embeddings_dataset(algo, loader, device=device, max_embs=0)

            valid = 0
            for Z in bundle["embeddings_list"]:
                Z = np.asarray(Z)
                if Z.ndim == 2 and len(Z) >= 2 and np.isfinite(Z).all():
                    valid += 1

            print("Valid videos:", valid)

            if valid > 0:
                print("Using checkpoint:", ckpt)
                return bundle, str(ckpt)

        except Exception as e:
            print("Failed:", repr(e))

    return None, None


cfg128 = make_run_config(embed_dim=128, max_iters=1000)
cfg128.logdir = "/content/runs_tutorial/pouring_tcc_d128"
cfg128.path_to_tfrecords = "/tmp/%s_tfrecords/"
cfg128.train.num_frames = 10
cfg128.eval.num_frames = 10
cfg128.data.frame_stride = 5

bundle128, ckpt128 = find_valid_checkpoint(cfg128)

print("Chosen checkpoint:", ckpt128)

emb_bundle128 = bundle128

import numpy as np

idx128 = None
for i, Z in enumerate(emb_bundle128["embeddings_list"]):
    Z = np.asarray(Z)
    if Z.ndim == 2 and len(Z) >= 2 and np.isfinite(Z).all():
        idx128 = i
        break

print("Using video index:", idx128)

Z128 = np.asarray(emb_bundle128["embeddings_list"][idx128])

plot_single_trajectory(Z128, method="pca", title="PCA trajectory (D=128)")

if HAS_UMAP:
    plot_single_trajectory(Z128, method="umap", title="UMAP trajectory (D=128)")

d128 = change_point_scores(Z128)
boundaries128, thr128 = detect_boundaries(d128, threshold_quantile=0.98, min_gap=8)
labels_km128 = cluster_kmeans(Z128, k=6)

plot_segmentation(Z128, labels=labels_km128, boundaries=boundaries128, title="KMeans k=6 (D=128)")

valid_embeddings = []
valid_names = []

for i, Z in enumerate(emb_bundle128["embeddings_list"]):
    Z = np.asarray(Z)
    if Z.ndim == 2 and len(Z) >= 2 and np.isfinite(Z).all():
        valid_embeddings.append(Z)
        if "names" in emb_bundle128:
            valid_names.append(emb_bundle128["names"][i])

plot_multiple_trajectories(
    valid_embeddings,
    valid_names if valid_names else None,
    method="umap" if HAS_UMAP else "pca"
)

"""### Cross-video trajectory overlay (UMAP)

This plot shows the trajectories of multiple pouring videos projected into a shared embedding space using UMAP. Each colored line represents the temporal trajectory of a single video as the task progresses.

We observe that the trajectories follow similar overall shapes across videos, even though they originate from different demonstrations. This suggests that the learned representation captures the underlying phase of the pouring task rather than simply memorizing appearance or video identity.

The alignment of trajectories across demonstrations supports the idea that TCC learns a shared temporal structure across videos performing the same task.
"""

!ls /content/runs_tutorial/pouring_tcc_d128

#extracting
cfg128 = make_run_config(embed_dim=128, max_iters=1000)
cfg128.logdir = "/content/runs_tutorial/pouring_tcc_d128"
cfg128.path_to_tfrecords = "/tmp/%s_tfrecords/"
cfg128.train.num_frames = 10
cfg128.eval.num_frames = 10
cfg128.data.frame_stride = 5

ckpt128 = "/content/runs_tutorial/pouring_tcc_d128/checkpoint_1000.pt"

algo, device, checkpoint_path = load_trained_algo(cfg128, checkpoint_path=ckpt128)
print("Loaded checkpoint:", checkpoint_path)

loader = make_eval_dataloader(cfg128, split="val", mode="eval")

from tcc.evaluate import get_embeddings_dataset
emb_bundle128 = get_embeddings_dataset(algo, loader, device=device, max_embs=0)

print("Videos:", len(emb_bundle128["embeddings_list"]))
print("Flat embedding shape:", emb_bundle128["embeddings"].shape)

#helper
import numpy as np

def clean_embeddings(Z, name="embedding"):
    Z = np.asarray(Z)
    print(f"{name} original shape:", Z.shape)
    print(f"{name} NaN count:", np.isnan(Z).sum())
    print(f"{name} Inf count:", np.isinf(Z).sum())

    keep = np.isfinite(Z).all(axis=1)
    Z_clean = Z[keep]

    print(f"{name} cleaned shape:", Z_clean.shape)

    if len(Z_clean) < 2:
        raise ValueError(f"{name} has fewer than 2 valid rows after cleaning.")

    return Z_clean, keep

"""## Comparison of D = 32, 64, 128

- **D = 32:** Produced stable embeddings and interpretable PCA/UMAP trajectories. It captures the coarse temporal progression of the pouring task, though phase separation is relatively compact.
- **D = 64:** Produced useful embeddings for analysis, with a better balance between compactness and expressiveness. The trajectories and segmentation results were easier to interpret than D = 32.
- **D = 128:** has the highest representational capacity. In my runs, it produced meaningful cross-video trajectories but occasionally showed instability in some checkpoints, suggesting that higher embedding dimensions may require longer training to remain stable.

Overall, D = 64 provided the best balance between representation capacity and stability.
"""

Z = emb_bundle32["embeddings_list"][1]
plot_single_trajectory(Z, method="pca", title="PCA trajectory video 2 (D=32)")
if HAS_UMAP:
    plot_single_trajectory(Z, method="umap", title="UMAP trajectory video 2 (D=32)")

"""### 7.1 Build the evaluation dataloader

The repo training code internally converts the top-level config into a `DataConfig`.  
We reuse the same helper if available; otherwise we build the `DataConfig` manually.
"""

def make_eval_dataloader(cfg, split="val", mode="eval"):
    """Build an evaluation dataloader from the top-level config.

    Uses the repo's internal _build_data_config helper.  If that helper
    is missing or its signature has changed, the call fails loudly so
    you know the notebook and repo are out of sync.
    """
    from tcc.datasets import create_dataset

    try:
        from tcc.train import _build_data_config
    except ImportError:
        raise ImportError(
            "Cannot import _build_data_config from tcc.train. "
            "The aegean-ai/tcc repo API may have changed. "
            "Check the repo README for the current evaluation interface."
        )

    data_cfg = _build_data_config(cfg)
    loader = create_dataset(split=split, mode=mode, config=data_cfg)
    return loader

def extract_embeddings_for_run(cfg, split="val", max_embs=0):
    """Extract embeddings from a trained checkpoint.

    Args:
        cfg: TCCConfig for the run.
        split: dataset split to evaluate ("val" or "train").
        max_embs: maximum number of video embeddings to extract.
                  0 means extract all available videos (no limit).
    """
    from tcc.evaluate import get_embeddings_dataset

    algo, device, checkpoint_path = load_trained_algo(cfg)
    loader = make_eval_dataloader(cfg, split=split, mode="eval")
    bundle = get_embeddings_dataset(algo, loader, device=device, max_embs=max_embs)

    print("Loaded checkpoint:", checkpoint_path)
    print("Videos:", len(bundle["embeddings_list"]))
    print("Flat embeddings shape:", bundle["embeddings"].shape)
    return bundle

# Example:
#cfg64 = make_run_config(embed_dim=64, max_iters=5000)
#emb_bundle = extract_embeddings_for_run(cfg64, split="val")

"""## 8. Representation diagnostics

Now we test the main scientific claim:

> Do embeddings organize frames by **task phase**?

We use two projection methods and two diagnostic approaches:

1. **PCA** — linear projection preserving global variance; fast and deterministic
2. **UMAP** — nonlinear projection revealing manifold structure; better for fine-grained phase separation

For each, we produce:

- **single-video trajectory plots** colored by time
- **cross-video overlays** in a shared projection space (joint fit, so coordinates are comparable)
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

try:
    import umap
    HAS_UMAP = True
except ImportError:
    HAS_UMAP = False

def project_pca(Z):
    return PCA(n_components=2).fit_transform(Z)

def project_umap(Z, seed=0):
    if not HAS_UMAP:
        raise ImportError("Install umap-learn: pip install umap-learn")
    return umap.UMAP(n_components=2, random_state=seed).fit_transform(Z)

def project(Z, method="umap", seed=0):
    if method == "pca":
        return project_pca(Z)
    if method == "umap":
        return project_umap(Z, seed=seed)
    raise ValueError(f"Unknown method: {method}. Use 'pca' or 'umap'.")

def plot_single_trajectory(Z, method="umap", title=None):
    Y = project(Z, method=method)
    t = np.arange(len(Y))

    plt.figure(figsize=(6, 5))
    sc = plt.scatter(Y[:, 0], Y[:, 1], c=t, s=12)
    plt.colorbar(sc, label="time")
    plt.xlabel("component 1")
    plt.ylabel("component 2")
    plt.title(title or f"{method.upper()} trajectory")
    plt.tight_layout()
    plt.show()

def plot_multiple_trajectories(embeddings_list, names=None, method="umap", max_videos=6):
    """Plot cross-video trajectories in a shared projection space.

    All video embeddings are concatenated, projected once, then split
    back so that the 2D coordinates are comparable across videos.
    """
    n = min(max_videos, len(embeddings_list))
    selected = embeddings_list[:n]
    lengths = [len(Z) for Z in selected]
    Z_all = np.concatenate(selected, axis=0)

    Y_all = project(Z_all, method=method, seed=0)

    splits = np.cumsum(lengths[:-1])
    Y_per_video = np.split(Y_all, splits)

    plt.figure(figsize=(7, 6))
    for i, Y in enumerate(Y_per_video):
        label = names[i] if names else f"video_{i}"
        plt.plot(Y[:, 0], Y[:, 1], alpha=0.8, label=label)
    plt.xlabel("component 1")
    plt.ylabel("component 2")
    plt.title(f"{method.upper()} cross-video trajectories (joint projection)")
    plt.legend(loc="best", fontsize=8)
    plt.tight_layout()
    plt.show()

# Example usage:
#
#emb_bundle = extract_embeddings_for_run(cfg64, split="val")
#Z0 = emb_bundle["embeddings_list"][0]
#plot_single_trajectory(Z0, method="pca", title="PCA trajectory")
#plot_single_trajectory(Z0, method="umap", title="UMAP trajectory")
#plot_multiple_trajectories(emb_bundle["embeddings_list"], emb_bundle["names"], method="umap")

"""## 9. Temporal segmentation from embedding geometry

This section operationalizes the claim that the embedding has learned latent phase.

We use two complementary segmentation strategies:

### 9.1 Change-point detection

If the representation changes rapidly at phase transitions, then
$$
d_t = \|z_t - z_{t-1}\|
$$
should spike near boundaries. This is a **boundary-detection** approach — it finds *where* phase transitions occur without assigning cluster labels.

### 9.2 KMeans clustering in the native embedding space

If the embedding clusters by phase, KMeans should recover coarse phase labels. We use $k=6$ to match the six expected pouring phases (reach, grasp, lift, tilt, pour, retract). Experiment with different $k$ values to test sensitivity.
"""

from sklearn.cluster import KMeans

def change_point_scores(Z):
    d = np.linalg.norm(Z[1:] - Z[:-1], axis=1)
    d = np.concatenate([[0.0], d])
    return d

def detect_boundaries(d, threshold_quantile=0.98, min_gap=10):
    thr = float(np.quantile(d, threshold_quantile))
    idx = np.where(d >= thr)[0].tolist()

    kept = []
    last = -10**9
    for i in idx:
        if i - last >= min_gap:
            kept.append(i)
            last = i
    return kept, thr

def cluster_kmeans(Z, k=6, seed=0):
    """KMeans with k=6 matching the six expected pouring phases."""
    return KMeans(n_clusters=k, random_state=seed, n_init="auto").fit_predict(Z)

def plot_segmentation(Z, labels=None, boundaries=None, title="Segmentation"):
    d = change_point_scores(Z)
    T = len(Z)

    plt.figure(figsize=(10, 3))
    plt.plot(np.arange(T), d)
    if boundaries is not None:
        for b in boundaries:
            plt.axvline(b, linestyle="--")
    plt.title(title + " — change-point score")
    plt.xlabel("frame index")
    plt.ylabel(r"$\|z_t-z_{t-1}\|$")
    plt.tight_layout()
    plt.show()

    if labels is not None:
        plt.figure(figsize=(10, 2))
        plt.plot(np.arange(T), labels, drawstyle="steps-mid")
        if boundaries is not None:
            for b in boundaries:
                plt.axvline(b, linestyle="--")
        plt.title(title + " — cluster labels over time")
        plt.xlabel("frame index")
        plt.ylabel("cluster")
        plt.tight_layout()
        plt.show()

# Example usage:
#
# Z = emb_bundle["embeddings_list"][0]
# d = change_point_scores(Z)
# boundaries, thr = detect_boundaries(d, threshold_quantile=0.98, min_gap=8)
# labels_km = cluster_kmeans(Z, k=6)
#
# plot_segmentation(Z, labels=labels_km, boundaries=boundaries, title="KMeans on native embeddings")

"""## 10. Embedding dimension sweep

The assignment asks you to compare:

- $D=32$
- $D=64$
- $D=128$

This matters because the embedding dimension controls the trade-off between:

- **compression**
- **expressiveness**
- **ease of clustering**
- **risk of overfitting appearance rather than phase**
"""

def run_full_analysis_for_dimension(embed_dim, max_iters=5000, split="val",
                                    max_embs=0, num_videos_to_analyze=3):
    """Run the complete analysis pipeline for one embedding dimension.

    Analyzes up to num_videos_to_analyze videos (not just the first one)
    to ensure results are not artifacts of a single video.
    """
    cfg = make_run_config(embed_dim=embed_dim, max_iters=max_iters)
    bundle = extract_embeddings_for_run(cfg, split=split, max_embs=max_embs)

    print(f"\n===== Dimension {embed_dim} =====")
    print("Number of videos:", len(bundle["embeddings_list"]))
    print("Flat embedding matrix:", bundle["embeddings"].shape)

    if len(bundle["embeddings_list"]) == 0:
        print("No embeddings found.")
        return cfg, bundle

    n_analyze = min(num_videos_to_analyze, len(bundle["embeddings_list"]))

    for vid_idx in range(n_analyze):
        Z = bundle["embeddings_list"][vid_idx]
        vid_name = bundle["names"][vid_idx] if "names" in bundle else f"video_{vid_idx}"
        tag = f"D={embed_dim}, {vid_name}"

        plot_single_trajectory(Z, method="pca", title=f"PCA trajectory ({tag})")
        if HAS_UMAP:
            plot_single_trajectory(Z, method="umap", title=f"UMAP trajectory ({tag})")

        d = change_point_scores(Z)
        boundaries, thr = detect_boundaries(d, threshold_quantile=0.98, min_gap=8)
        labels_km = cluster_kmeans(Z, k=6)
        plot_segmentation(Z, labels=labels_km, boundaries=boundaries,
                          title=f"KMeans k=6 ({tag})")

    # Cross-video overlay (joint projection)
    if HAS_UMAP and len(bundle["embeddings_list"]) > 1:
        plot_multiple_trajectories(bundle["embeddings_list"], bundle.get("names"),
                                   method="umap")

    return cfg, bundle

# Example:
# cfg64, bundle64 = run_full_analysis_for_dimension(64, max_iters=5000)

"""## 11. Write-up questions

### Q1. TCN vs TCC
Explain, in your own words, the evolution from TCN to TCC. Include the role of the soft nearest-neighbor formulation in making cycle consistency differentiable.

### Q2. Does the learned representation encode phase?
Use your PCA and UMAP plots to justify a claim. Compare single-video trajectories with cross-video overlays.

### Q3. How well does segmentation recover phase structure?
Compare change-point detection and KMeans clustering. Do the detected boundaries align with qualitative phase transitions? Does varying $k$ change the story?

### Q4. What failure modes remain?
Examples:

- appearance variation dominating phase
- pauses causing over-segmentation
- self-similar frames across non-adjacent stages
- collapse of distinct phases into one cluster

## Answer 1
The Time-Contrastive Networks (TCN) and Temporal Cycle-Consistency Learning (TCC) methods are similar in the sense that they attempt to learn action representations from videos. The main difference between the two is the manner in which the videos are temporally aligned.

TCN

TCN learns representations by considering frames at the same temporal stage of different videos as positive pairs, while frames at different stages are treated as negative pairs. The rationale is that frames of the same action stage, such as the beginning of the action of pouring, should have similar representations despite the videos.

The problem with TCN is the fact that it requires the videos to be aligned. If the videos of the action are performed at different rates, the model may misclassify the frames.

TCC

TCC improves on the limitations of the previous method by incorporating the concept of cycle consistency between videos. The model is able to detect the consistency between the frames of the videos.

The process looks like this:

A frame from video A is matched to the closest frame in video B.

The matched frame in video B is then matched to the closest frame back in video A.

If the representation is good, the cycle should eventually return to the original frame.

This basic idea allows the model to automatically learn the alignment of the videos even if they have different speeds or lengths.

**Role of Soft Nearest Neighbor**

One problem with the basic idea of the nearest neighbor is that the operation is typically non-differentiable, which would prevent the model from being learned with gradient methods.

TCC overcomes this problem through the use of a soft version of the nearest neighbor. Instead of finding the single closest frame to a given frame, the model computes a soft probability distribution over all possible frames through the use of a similarity function and a temperature parameter.

This operation is continuous and differentiable, which allows the gradients to flow through the cycle consistency objective during training.

## Answer 2
Yes, it seems to. Evidence from PCA & UAP The embeddings can also be visualized using PCA & UAP. Single Video Trajectories If we plot the embeddings of a single video over time, we notice a trajectory. The trajectory is smooth, meaning that there is no sudden jump. This implies that if we take consecutive frames, they are likely to be close to each other. This is evidence that the learned representation has encoded the passage of time while performing the task. The task progression can be described as follows:

Initial state

Tilt the container

Pouring action

Ending state or returning to resting state

Overlaid Trajectories for Multiple Videos If we plot the embeddings of multiple videos, we notice that frames corresponding to particular phases of the action cluster together. This is despite the fact that we are using different videos. This is evidence that a phase-based representation has been learned, as opposed to a video-based representation. For example, we notice that early frames cluster together, then there is a cluster of frames corresponding to the action of pouring, while yet another cluster corresponds to the ending state.

## Answer 3
Temporal segmentation was carried out using two techniques:

change-point detection
K-means clustering
Change Point Detection
Change-point detection is a technique used to detect points where the embedding trajectory is experiencing a significant change.

Most of the time, the boundaries identified by the algorithm coincide with apparent changes in the action, such as:

the start of tilting the container
the start of pouring
the end of pouring
Since the embedding trajectory is continuous and smooth over time, the boundaries are usually identified when the trajectory is experiencing a change in direction.

K-Means Clustering
K-means clustering is a technique used to segment the embedding into distinct clusters corresponding to different phases of the action.

If the number of clusters is appropriately selected as a range of 3 to 5,
k
k clusters, the clusters identified by the algorithm usually correspond to important phases such as:

preparation
pouring
finishing
However, K-means clustering does not take into account the time dimension and hence might include frames from different time points when the frames appear to be similar in appearance.

Effect of Changing k
The choice of k has the following effect on the results of the segmentation:

small k values, e.g., 2-3, combine several phases into a single segment

moderate k values, e.g., 4-5, seem to work best with meaningful stages of action

large k values, e.g., 8 or more, may over-segment the video into too many phases

In general, the two approaches seem to capture important aspects of the task structure, although the change point detection boundaries tend to line up more closely with transitions in the action.

## Answer 4

Although the model has improved the temporal alignment of the videos, there are several failure modes.

**1. Appearance Variation Dominating Phase**

The model may focus more on the appearance differences instead of the phase differences.

Examples:

* Different colors of the cup
* Lighting changes
* Different backgrounds

As a result, the model may map frames with similar appearances even if they do not have similar phases.

**2. Pauses Causing Over-Segmentation**

If the subject pauses in the action, such as holding the container before pouring, the embedding may change even if the phase has not changed.

Change point detection may consider it a new phase, which leads to over-segmentation.

**3. Self-Similar Frames Across Different Stages**

There are frames in the videos that look similar even though they are from different stages of the action.

Examples:

* Container is upright before pouring
* Container is upright after pouring

The frames look similar, which may cause the model to map the frames to similar locations in the embedding space, causing the model to incorrectly map the early and late stages.

**4. Phase Collapse**

If the embedding dimension or the training signal is insufficient, several phases of the task can collapse into the same cluster.

For example:

Preparation and pouring can fall into the same cluster.

If the embedding has insufficient capacity or the training signal does not strongly separate the phases, this can occur.

**Conclusion**

The TCC approach has several advantages over the traditional TCN approach. It learns temporal alignment based on cycle consistency and soft nearest neighbor matching. The learned embeddings have the ability to capture the progression of phases in the action. This can be observed in the PCA and UMAP visualization of the learned embeddings. The segmentation approaches such as change point detection and K-means can partially recover the phase structure of the task. However, there are some issues that need to be addressed.

### Implementation Notes

During the process of running the experiments, I occasionally deviated slightly from the exact notebook code provided in order to obtain stable and successful runs. In particular, I added small variations to configuration settings (such as checkpoint selection and embedding extraction) when necessary to ensure that the training and evaluation pipelines completed correctly.

Additionally, because I am currently enrolled in both *AI for Robotics* and *Deep Learning for Computer Vision*, both of which require computationally intensive experiments, I encountered limitations with available GPU resources during execution. My access to higher-tier GPUs (such as T4, A100, and H100) was exhausted during some runs, which required me to temporarily downsize certain training configurations (for example reducing the number of iterations or selecting earlier checkpoints) in order to complete the experiments within the available compute budget.

These adjustments were made only when necessary to ensure that the experiments could be executed successfully while still preserving the overall methodology and analysis required for the assignment.

## 12. Final checklist

Before submitting, verify that you have:

- trained at least one real TCC run on pouring
- extracted embeddings from a saved checkpoint
- produced PCA and UMAP trajectory plots for multiple videos
- produced a cross-video overlay using joint projection
- run both change-point detection and KMeans segmentation
- compared $D=32,64,128$
- written answers to all four questions (Q1–Q4) in inline markdown cells, with all supporting figures embedded in the notebook

That completes the assignment.

Author:
Shivangi Srivastava

UCID: ss5554

Course: AI for Robotics
"""